championsName = {"이즈리얼" : "Ezreal", "이즈" : "Ezreal", "진" : "Jhin", "리신" : "LeeSin", "리 신" : "LeeSin", "징크스" : "Jinx",
             "케이틀린" : "Caitlyn", "케틀" : "Caitlyn", "제이스" : "Jayce", "그레이브즈" : "Graves", "그브" : "Graves",
             "카이사" : "Kaisa", "쓰레쉬" : "Thresh", "럭스" : "Lux", "블리츠크랭크" : "Blitzcrank", "블랭" : "Blitzcrank",
             "블츠" : "Blitzcrank", "탈론" : "Talon", "룰루" : "Lulu", "베인" : "Vayne", "제라스" : "Xerath", "요네" : "Yone",
             "제드" : "Zed", "르블랑" : "Leblanc", "루시안" : "Lucian", "빅토르" : "Viktor", "야스오" : "Yasuo", "레오나" : "Leona",
             "유미" : "Yuumi", "비에고" : "Viego", "사미라" : "Samira", "이렐리아" : "Irelia", "이렐" : "Irelia", "아칼리" : "Akali",
             "카밀" : "Camille", "아트록스" : "Aatrox", "아트" : "Aatrox", "잭스" : "Jax", "피오라" : "Fiora", "세트" : "Sett", "다리우스" : "Darius",
             "다리" : "Darius", "티모" : "Teemo", "말파이트" : "Malphite", "말파" : "Malphite", "탐켄치" : "TahmKench",
             "탐켄치" : "TahmKench", "사일러스" : "Sylas", "사일" : "Sylas", "레넥톤" : "Renekton", "레넥" : "Renekton",
             "그웬" : "Gwen", "가렌" : "Garen", "케넨" : "Kennen", "갱플랭크" : "Gangplank", "갱플" : "Gangplank",
             "리븐" : "Riven", "오른" : "Ornn", "트린다미어" : "Tryndamere", "트린" : "Tryndamere", "쉔" : "Shen",
             "나서스" : "Nasus", "문도" : "DrMundo", "문도박사" : "DrMundo", "문도 박사" : "DrMundo", "모데카이저" : "Mordekaiser",
             "모데" : "Mordekaiser", "렝가" : "Rengar", "뽀삐" : "Poppy", "나르" : "Gnar", "라이즈" : "Ryze", "사이온" : "Sion",
             "트런들" : "Trundle", "아크샨" : "Akshan", "케일" : "Kayle", "오공" : "MonkeyKing", "블라디미르" : "Vladimir",
             "블라디" : "Vladimir", "볼리베어" : "Volibear", "볼베" : "Volibear", "일라오이" : "Illaoi", "일라" : "Illaoi",
             "클레드" : "Kled", "우르곳" : "Urgot", "그라가스" : "Gragas", "그라" : "Gragas", "워윅" : "Warwick",
             "워웍" : "Warwick", "위윅" : "Warwick", "위웍" : "Warwick", "퀸" : "Quinn", "요릭" : "Yorick", "럼블" : "Rumble",
             "신지드" : "Singed", "싱드" : "Singed", "하이머딩거" : "Heimerdinger", "하딩" : "Heimerdinger",
             "딩거" : "Heimerdinger", "초가스" : "Chogath", "카시오페아" : "Cassiopeia", "카시" : "Cassiopeia",
             "마오카이" : "Maokai", "마오" : "Maokai", "자크" : "Zac", "릴리아" : "Lillia", "피즈" : "Fizz",
             "판테온" : "Pantheon", "판테" : "Pantheon", "신짜오" : "XinZhao", "신 짜오" : "XinZhao",
             "짱깨" : "XinZhao", "짜오" : "XinZhao", "마스터이" : "MasterYi", "마스터 이" : "MasterYi", "마이" : "MasterYi",
             "칼리스타" : "Kalista", "칼리" : "Kalista", "드레이븐" : "Draven", "드븐" : "Draven", "카르마" : "Karma",
             "세주아니" : "Sejuani", "세주" : "Sejuani", "말자하" : "Malzahar", "말자" : "Malzahar", "에코" : "Ekko",
             "올라프" : "Olaf", "케인" : "Kayn", "코르키" : "Corki", "콜키" : "Corki", "쉬바나" : "Shyvana",
             "노틸러스" : "Nautilus", "노틸" : "Nautilus", "니달리" : "Nidalee", "킨드레드" : "Kindred", "킨드" : "Kindred",
             "샤코" : "Shaco", "자르반4세" : "JarvanIV", "자르반" : "JarvanIV", "자르반 4세" : "JarvanIV", "엘리스" : "Elise",
             "카직스" : "Khazix", "헤카림" : "Hecarim", "누누" : "Nunu", "누누와윌럼프" : "Nunu", "누누와 윌럼프" : "Nunu",
             "누누와월럼프" : "Nunu", "누누와 월럼프" : "Nunu", "바이" : "Vi", "렉사이" : "RekSai", "녹턴" : "Nocturne",
             "피들스틱" : "Fiddlesticks", "피들" : "Fiddlesticks", "이블린" : "Evelynn", "카서스" : "Karthus",
             "다이애나" : "Diana", "다애" : "Diana", "람머스" : "Rammus", "람머" : "Rammus”", "탈리야" : "Taliyah",
             "키아나" : "Qiyana", "아무무" : "Amumu", "무무" : "Amumu", "우디르" : "Udyr", "아이번" : "Ivern",
             "트위치" : "Twitch", "스카너" : "Skarner", "트위스티드페이트" : "TwistedFate", "트위스티드 페이트" : "TwistedFate",
             "트페" : "TwistedFate", "벡스" : "Vex", "카타리나" : "Katarina", "카타" : "Katarina", "아리" : "Ahri",
             "신드라" : "Syndra", "조이" : "Zoe", "오리아나" : "Orianna", "오리" : "Orianna", "리산드라" : "Lissandra",
             "리산" : "Lissandra", "애니비아" : "Anivia", "갈리오" : "Galio", "아지르" : "Azir", "베이가" : "Veigar",
             "애니" : "Annie", "아우렐리온솔" : "AurelionSol", "아우렐리온 솔" : "AurelionSol", "아우솔" : "AurelionSol",
             "브랜드" : "Brand", "니코" : "Neeko", "파이크" : "Pyke", "모르가나" : "Morgana", "몰가" : "Morgana",
             "직스" : "Ziggs", "질리언" : "Zilean", "트리스타나" : "Tristana", "트타" : "Tristana", "아펠리오스" : "Aphelios",
             "아펠" : "Aphelios", "애쉬" : "Ashe", "미스 포츈" : "MissFortune", "미스포츈" : "MissFortune",
             "미포" : "MissFortune", "자야" : "Xayah", "바루스" : "Varus", "시비르" : "Sivir", "코그모" : "KogMaw",
             "세나" : "Senna", "스웨인" : "Swain", "알리스타" : "Alistar", "알리" : "Alistar", "나미" : "Nami",
             "소라카" : "Soraka", "라칸" : "Rakan", "자이라" : "Zyra", "브라움" : "Braum", "잔나" : "Janna", "바드" : "Bard",
             "렐" : "Rell", "소나" : "Sona", "세라핀" : "Seraphine", "시진핑" : "Seraphine", "타릭" : "Taric", "아무무" : "Amumu",
             # 추가된 챔피언들
             "벨베스" : "Belveth" , "브라이어" : "Briar", "제리" : "Zeri", "크산테" : "KSante", "밀리오" : "Milio", "닐라" : "Nilah", "나피리" : "Naafiri",
             "레나타 글라스크" : "RenataGlasc", "레나타" : "RenataGlasc", "흐웨이" : "Hwei"
             }

def find_kor_name(english_name):
    # champions 딕셔너리를 순회하며 영어 이름과 일치하는 한글 이름 찾기
    for kor, eng in championsName.items():
        if eng == english_name:
            return kor  # 일치하는 한글 이름 반환
    return None  # 일치하는 항목이 없으면 None 반환